client_config_backend: settings
client_config:
  client_id: __YOUR_APP_CLIENT_ID__
  client_secret: __YOUR_APP_CLIENT_SECRET__

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive.readonly

xml_file: gdrive_git.xml
